# Generated by Django 2.0.5 on 2018-05-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_content',
        ),
    ]
